import type { BulkTier, Product } from "./types";

export const BULK_TIERS: BulkTier[] = [
  { min: 1, discount: 0, label: "۱–۹ عدد" },
  { min: 10, discount: 0.1, label: "۱۰–۴۹ عدد (۱۰٪ تخفیف)" },
  { min: 50, discount: 0.2, label: "۵۰–۹۹ عدد (۲۰٪ تخفیف)" },
  { min: 100, discount: 0.3, label: "۱۰۰+ عدد (۳۰٪ تخفیف)" },
];

/** Seed data — used for initial database seeding and as JSON fallback */
export const SEED_PRODUCTS: Product[] = [
  {
    id: "heart-badge",
    name: "بج قلب مهربان",
    nameEn: "Kind Heart Badge",
    description: "عروسک کوچک قلب صورتی — برای همکار مهربانی که همیشه حمایت می‌کند",
    price: 45000,
    emoji: "💗",
    color: "#fce7f3",
    traits: ["kind", "empathetic"],
    occasion: ["تولد", "تشکر", "قدردانی"],
    size: "۱.۵ سانتی‌متر",
  },
  {
    id: "lightbulb-badge",
    name: "بج ایده خلاق",
    nameEn: "Creative Lightbulb",
    description: "لامپ کوچک درخشان — برای کسی که همیشه ایده‌های نو دارد",
    price: 45000,
    emoji: "💡",
    color: "#ede9fe",
    traits: ["creative", "bold"],
    occasion: ["تولد", "ارتقا", "پروژه جدید"],
    size: "۱.۸ سانتی‌متر",
  },
  {
    id: "crown-badge",
    name: "بج تاج رهبر",
    nameEn: "Leader Crown",
    description: "تاج طلایی مینیاتوری — برای رهبر تیم و الهام‌بخش",
    price: 55000,
    emoji: "👑",
    color: "#fef3c7",
    traits: ["leader", "bold"],
    occasion: ["ارتقا", "تولد", "پایان پروژه"],
    size: "۲ سانتی‌متر",
  },
  {
    id: "star-badge",
    name: "بج ستاره درخشان",
    nameEn: "Shining Star",
    description: "ستاره طلایی — برای همکار برجسته و مثبت‌اندیش",
    price: 50000,
    emoji: "⭐",
    color: "#fef9c3",
    traits: ["optimistic", "energetic"],
    occasion: ["تولد", "تشکر", "پایان پروژه"],
    size: "۱.۵ سانتی‌متر",
  },
  {
    id: "coffee-badge",
    name: "بج قهوه صبور",
    nameEn: "Patient Coffee",
    description: "فنجان قهوه کوچک — برای کسی که با صبر و حوصله کار می‌کند",
    price: 40000,
    emoji: "☕",
    color: "#f5f5f4",
    traits: ["patient", "organized"],
    occasion: ["تولد", "تشکر"],
    size: "۱.۲ سانتی‌متر",
  },
  {
    id: "rocket-badge",
    name: "بج موشک پرانرژی",
    nameEn: "Energetic Rocket",
    description: "موشک پرسرعت — برای همکار پرانرژی و پرشور",
    price: 50000,
    emoji: "🚀",
    color: "#ffedd5",
    traits: ["energetic", "bold", "optimistic"],
    occasion: ["پروژه جدید", "تولد", "ارتقا"],
    size: "۲ سانتی‌متر",
  },
  {
    id: "puzzle-badge",
    name: "بج پازل دقیق",
    nameEn: "Meticulous Puzzle",
    description: "قطعه پازل — برای کسی که به جزئیات اهمیت می‌دهد",
    price: 45000,
    emoji: "🧩",
    color: "#e0e7ff",
    traits: ["meticulous", "organized"],
    occasion: ["پایان پروژه", "تشکر"],
    size: "۱.۵ سانتی‌متر",
  },
  {
    id: "laugh-badge",
    name: "بج خنده شوخ‌طبع",
    nameEn: "Humorous Laugh",
    description: "ایموجی خنده — برای شوخ‌طبع تیم که فضا را شاد می‌کند",
    price: 40000,
    emoji: "😂",
    color: "#fef08a",
    traits: ["humorous", "optimistic"],
    occasion: ["تولد", "جشن تیم"],
    size: "۱.۵ سانتی‌متر",
  },
  {
    id: "handshake-badge",
    name: "بج دست وفادار",
    nameEn: "Loyal Handshake",
    description: "دست دادن مینیاتوری — برای همکار وفادار و قابل اعتماد",
    price: 45000,
    emoji: "🤝",
    color: "#ccfbf1",
    traits: ["loyal", "kind", "empathetic"],
    occasion: ["سالگرد همکاری", "تشکر", "قدردانی"],
    size: "۱.۸ سانتی‌متر",
  },
  {
    id: "magnifier-badge",
    name: "بج ذره‌بین دقیق",
    nameEn: "Detail Magnifier",
    description: "ذره‌بین کوچک — برای کسی که هیچ جزئیاتی را از دست نمی‌دهد",
    price: 45000,
    emoji: "🔍",
    color: "#ddd6fe",
    traits: ["meticulous", "patient"],
    occasion: ["پایان پروژه", "تشکر"],
    size: "۱.۵ سانتی‌متر",
  },
  {
    id: "bear-badge",
    name: "بج خرس همدل",
    nameEn: "Empathetic Bear",
    description: "خرس کوچک بامزه — برای همکار همدل و دلسوز",
    price: 50000,
    emoji: "🧸",
    color: "#fbcfe8",
    traits: ["empathetic", "kind", "patient"],
    occasion: ["تولد", "حمایت", "تشکر"],
    size: "۲ سانتی‌متر",
  },
  {
    id: "lion-badge",
    name: "بج شیر جسور",
    nameEn: "Bold Lion",
    description: "شیر کوچک شجاع — برای کسی که بدون ترس جلو می‌رود",
    price: 55000,
    emoji: "🦁",
    color: "#fed7aa",
    traits: ["bold", "leader", "energetic"],
    occasion: ["ارتقا", "پروژه جدید", "تولد"],
    size: "۲ سانتی‌متر",
  },
  {
    id: "clipboard-badge",
    name: "بج کلیپ‌بورد منظم",
    nameEn: "Organized Clipboard",
    description: "کلیپ‌بورد مینیاتوری — برای همکار منظم و سازمان‌یافته",
    price: 40000,
    emoji: "📋",
    color: "#bfdbfe",
    traits: ["organized", "meticulous"],
    occasion: ["تشکر", "پایان پروژه"],
    size: "۱.۵ سانتی‌متر",
  },
  {
    id: "rainbow-badge",
    name: "بج رنگین‌کمان مثبت",
    nameEn: "Optimistic Rainbow",
    description: "رنگین‌کمان کوچک — برای مثبت‌اندیس‌ترین نفر تیم",
    price: 45000,
    emoji: "🌈",
    color: "#e9d5ff",
    traits: ["optimistic", "creative", "humorous"],
    occasion: ["تولد", "جشن تیم"],
    size: "۱.۸ سانتی‌متر",
  },
  {
    id: "trophy-badge",
    name: "بج جام قهرمان",
    nameEn: "Champion Trophy",
    description: "جام طلایی مینیاتوری — برای قهرمان تیم و برنده",
    price: 60000,
    emoji: "🏆",
    color: "#fde68a",
    traits: ["leader", "bold", "energetic"],
    occasion: ["پایان پروژه", "ارتقا", "جشن تیم"],
    size: "۲ سانتی‌متر",
  },
  {
    id: "music-badge",
    name: "بج نت موسیقی خلاق",
    nameEn: "Creative Music Note",
    description: "نت موسیقی — برای همکار خلاق و هنرمند",
    price: 45000,
    emoji: "🎵",
    color: "#c4b5fd",
    traits: ["creative", "humorous", "optimistic"],
    occasion: ["تولد", "جشن تیم"],
    size: "۱.۵ سانتی‌متر",
  },
  {
    id: "fire-badge",
    name: "بج شعله پرشور",
    nameEn: "Passionate Fire Badge",
    description: "شعله کوچک درخشان — برای همکار پرشور و انگیزه‌بخشی که به تیم گرما می‌دهد",
    price: 50000,
    emoji: "🔥",
    color: "#ffedd5",
    traits: ["energetic", "bold"],
    occasion: ["پروژه جدید", "تولد", "تشکر"],
    size: "۱.۵ سانتی‌متر",
  },
  {
    id: "owl-badge",
    name: "بج جغد دانا",
    nameEn: "Wise Owl Badge",
    description: "جغد مینیاتوری — برای مرجع دانایی و مشاور صبور تیم",
    price: 45000,
    emoji: "🦉",
    color: "#f1f5f9",
    traits: ["patient", "meticulous"],
    occasion: ["قدردانی", "سالگرد همکاری", "تشکر"],
    size: "۱.۸ سانتی‌متر",
  },
  {
    id: "shield-badge",
    name: "بج سپر پشتیبان",
    nameEn: "Protector Shield Badge",
    description: "سپر مینیاتوری — برای همکار قابل اعتمادی که همیشه پشتیبان تیم است",
    price: 50000,
    emoji: "🛡️",
    color: "#e0f2fe",
    traits: ["loyal", "empathetic"],
    occasion: ["تشکر", "قدردانی", "سالگرد همکاری"],
    size: "۲ سانتی‌متر",
  },
  {
    id: "palette-badge",
    name: "بج پالت هنرمند",
    nameEn: "Artist Palette Badge",
    description: "پالت رنگی کوچک — برای زیبانگار و طراح خوش‌ذوق تیم",
    price: 45000,
    emoji: "🎨",
    color: "#f3e8ff",
    traits: ["creative", "optimistic"],
    occasion: ["تولد", "پروژه جدید", "تشکر"],
    size: "۱.۸ سانتی‌متر",
  },
  {
    id: "target-badge",
    name: "بج سیبل هدفمند",
    nameEn: "Focused Target Badge",
    description: "سیبل و تیر مینیاتوری — برای کسی که همیشه صاف به هدف می‌زند",
    price: 45000,
    emoji: "🎯",
    color: "#fee2e2",
    traits: ["organized", "meticulous", "bold"],
    occasion: ["پایان پروژه", "ارتقا", "تشکر"],
    size: "۱.۵ سانتی‌متر",
  },
  {
    id: "battery-badge",
    name: "بج باتری پرشارژ",
    nameEn: "Full Battery Badge",
    description: "باتری سبز و کامل — برای کسی که خستگی نمی‌شناسد و همیشه انرژی دارد",
    price: 40000,
    emoji: "🔋",
    color: "#dcfce7",
    traits: ["energetic", "optimistic"],
    occasion: ["تولد", "پروژه جدید", "جشن تیم"],
    size: "۱.۵ سانتی‌متر",
  },
  {
    id: "clover-badge",
    name: "بج شبدر خوش‌شانس",
    nameEn: "Lucky Clover Badge",
    description: "شبدر چهاربرگ — برای کسی که با آمدنش برای تیم شانس و برکت می‌آورد",
    price: 45000,
    emoji: "🍀",
    color: "#d1fae5",
    traits: ["optimistic", "kind"],
    occasion: ["تولد", "پروژه جدید", "تبریک"],
    size: "۱.۵ سانتی‌متر",
  },
  {
    id: "gem-badge",
    name: "بج الماس ارزشمند",
    nameEn: "Precious Gem Badge",
    description: "الماس درخشان مینیاتوری — برای گوهر کمیاب و همکار گرانبهای تیم",
    price: 60000,
    emoji: "💎",
    color: "#e0f2fe",
    traits: ["loyal", "leader", "meticulous"],
    occasion: ["سالگرد همکاری", "ارتقا", "قدردانی"],
    size: "۱.۵ سانتی‌متر",
  },
  {
    id: "seedling-badge",
    name: "بج جوانه رشد",
    nameEn: "Growth Seedling Badge",
    description: "جوانه سبز مینیاتوری — برای همکاری که همیشه در حال یادگیری و رشد است",
    price: 40000,
    emoji: "🌱",
    color: "#ecfdf5",
    traits: ["patient", "creative", "optimistic"],
    occasion: ["ورود همکار جدید", "تولد", "ارتقا"],
    size: "۱.۲ سانتی‌متر",
  },
  {
    id: "compass-badge",
    name: "بج قطب‌نمای راهنما",
    nameEn: "Guiding Compass Badge",
    description: "قطب‌نمای مینیاتوری — برای کسی که مسیر درست را در چالش‌ها نشان می‌دهد",
    price: 50000,
    emoji: "🧭",
    color: "#e0e7ff",
    traits: ["leader", "organized", "patient"],
    occasion: ["ارتقا", "تشکر", "قدردانی"],
    size: "۱.۸ سانتی‌متر",
  },
  {
    id: "cake-badge",
    name: "بج کیک جشن",
    nameEn: "Celebration Cake Badge",
    description: "کیک کوچک با شمع — ویژه تبریک تولد و جشن‌های شیرین تیم",
    price: 45000,
    emoji: "🎂",
    color: "#fce7f3",
    traits: ["humorous", "kind", "optimistic"],
    occasion: ["تولد", "جشن تیم"],
    size: "۱.۸ سانتی‌متر",
  },
  {
    id: "cat-badge",
    name: "بج گربه آرام",
    nameEn: "Calm Cat Badge",
    description: "گربه مینیاتوری ناز — برای همکار آرام، دوست‌داشتنی و صبور",
    price: 45000,
    emoji: "🐱",
    color: "#ffe4e6",
    traits: ["patient", "kind", "empathetic"],
    occasion: ["تولد", "تشکر"],
    size: "۱.۸ سانتی‌متر",
  },
  {
    id: "sun-badge",
    name: "بج خورشید پرنور",
    nameEn: "Radiant Sun Badge",
    description: "خورشید طلایی خندان — برای کسی که با لبخندش روز همه را روشن می‌کند",
    price: 50000,
    emoji: "☀️",
    color: "#fef3c7",
    traits: ["optimistic", "energetic", "kind"],
    occasion: ["تولد", "تشکر", "قدردانی"],
    size: "۲ سانتی‌متر",
  },
  {
    id: "medal-badge",
    name: "بج مدال افتخار",
    nameEn: "Honor Medal Badge",
    description: "مدال طلایی با روبان — برای قدردانی از دستاوردهای فوق‌العاده",
    price: 55000,
    emoji: "🏅",
    color: "#fef08a",
    traits: ["leader", "bold", "meticulous"],
    occasion: ["پایان پروژه", "ارتقا", "سالگرد همکاری"],
    size: "۲ سانتی‌متر",
  },
];

/** Backward-compatible alias */
export const PRODUCTS = SEED_PRODUCTS;

export function getProductById(id: string): Product | undefined {
  return SEED_PRODUCTS.find((p) => p.id === id);
}

export function getProductsByTrait(trait: string): Product[] {
  return SEED_PRODUCTS.filter((p) => p.traits.includes(trait as Product["traits"][number]));
}

export function getBulkDiscount(quantity: number): number {
  let discount = 0;
  for (const tier of BULK_TIERS) {
    if (quantity >= tier.min) discount = tier.discount;
  }
  return discount;
}

export function calculatePrice(unitPrice: number, quantity: number): number {
  const discount = getBulkDiscount(quantity);
  return Math.round(unitPrice * quantity * (1 - discount));
}

export function formatPrice(price: number): string {
  return new Intl.NumberFormat("fa-IR").format(price) + " تومان";
}
